/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_multicast_music_InternalSpeaker */

#ifndef _Included_com_multicast_music_InternalSpeaker
#define _Included_com_multicast_music_InternalSpeaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_multicast_music_InternalSpeaker
 * Method:    beepPCSpeaker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_multicast_1music_InternalSpeaker_beepPCSpeaker
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
